config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get '/'                             => 'employees#home'
  get 'report'                        => 'admin#issue'
  post 'report_deliver'               => 'admin#issue_deliver'
  get 'feedback'                      => 'admin#feedback'
  post 'feedback_deliver'             => 'admin#feedback_deliver'

  get 'employees'                     => 'employees#index'
  get 'employees/team'                => 'employees#team'
  get 'employees/import'              => 'employees#import'
  get 'employees/change'              => 'employees#change_password'
  get 'employees/change/complete'     => 'employees#change_password_finish'
  post 'employees/change/complete'    => 'employees#change_password_finish'
  get 'employees/:id'                 => 'employees#show', as: :employee
  get 'employees/:id/achievements'    => 'employees#achievements'
  get 'employees/analyze/:id'         => 'employees#analyze'

  get 'bucks'                         => 'bucks#index'
  get 'bucks/new'                     => 'bucks#new'
  get 'bucks/import'                  => 'bucks#import'
  post 'bucks'                        => 'bucks#create'
  get 'bucks/issued'                  => 'bucks#issued'
  get 'bucks/pending'                 => 'bucks#pending'
  get 'bucks/pending/:id'             => 'bucks#approve'
  post 'bucks/pending/:id'            => 'bucks#update'
  get 'bucks/:id'                     => 'bucks#show', as: :buck
  post 'bucks/new'                    => 'bucks#search'
  get 'bucks/delete/:id'              => 'bucks#delete'

  get 'purchase/start_manage'         => 'purchases#start_manage'
  get 'purchase/start_purchase'       => 'purchases#start_purchase'
  get 'purchase/manage'               => 'purchases#manage'
  get 'purchase/refund'               => 'purchases#refund'
  get 'purchase/finish/:id'           => 'purchases#finish'
  post 'purchase/finish/:id'          => 'purchases#complete'
  get 'purchase/reserved'             => 'purchases#reserved'
  get 'exchange'                      => 'purchases#exchange'

  get 'prizes'                        => 'prizes#index'
  get 'prizes/orders'                 => 'purchases#orders_personal'
  get 'prizes/manage'                 => 'prizes#manage'
  get 'prizes/new'                    => 'prizes#new'
  post 'prizes'                       => 'prizes#create'
  get 'prizes/edit/:id'               => 'prizes#edit'
  get 'prizes/:id'                    => 'prizes#show'
  post 'prizes/:id'                   => 'purchases#complete'
  post 'prizes/edit/:id'              => 'prizes#update'
  get 'prizes/discontinue/:id'        => 'prizes#discontinue'
  get 'prizes/:id/stock'              => 'prizes#stock'

  get 'prizes/manage/:id'             => 'prize_subcats#manage'
  post 'prizes/manage/:id'            => 'prize_subcats#create'
  get 'prizes/manage/:id/new'         => 'prize_subcats#new'
  get 'prizes/manage/type/:id'        => 'prize_subcats#edit'
  post 'prizes/manage/type/:id'       => 'prize_subcats#update'

  get 'jobs'                          => 'jobs#index'
  get 'jobs/import'                   => 'jobs#import'

  get 'login'                         => 'sessions#new'
  post 'login'                        => 'sessions#create'
  get 'logout'                     => 'sessions#destroy'

  get 'admin/depts'                   => 'departments#edit'
  post 'admin/depts'                  => 'departments#update'
  get 'admin/depts/approver'          => 'departments#approvers'
  get 'admin/depts/approver_add'      => 'departments#approver_add'
  get 'admin/logs/bucks'              => 'bucks#logs'
  get 'admin/logs/store'              => 'prizes#logs'
  get 'admin/bucks/analyze'           => 'bucks#analyze'
  get 'admin/orders'                  => 'purchases#orders'
  get 'admin/orders/pickup/:id'       => 'purchases#pickup'
  get 'admin/orders/drop/:id'         => 'purchases#drop'
  get 'admin/orders/confirm/:id'      => 'purchases#confirm'
  get 'admin/hard_reset'              => 'override#verify'
  get 'admin/hard_reset/:key'         => 'override#process'

  get 'mail/optout/:id'               => 'mailer#opt_out'

  get 'roles'                         => 'roles#index'
  get 'roles/new'                     => 'roles#new'
  get 'roles/edit/:id'                => 'roles#edit'
  get 'roles/assign/:id'              => 'roles#assign'
  post 'roles/edit/:id'               => 'roles#update'
  post 'roles'                        => 'roles#create'
  get 'roles/assign/:id/add'          => 'roles#add_to_role'
  get 'roles/assign/:id/remove'       => 'roles#remove_from_role'
  get 'roles/delete/:id'              => 'roles#delete'

  get 'favorites'                     => 'favorites#index'
  get 'favorites/create/'             => 'favorites#create'
  get 'favorites/delete'              => 'favorites#delete'

end

app/controllers/prizes_controller.rb
class PrizesController < ApplicationController
	include SessionsHelper
	include PrizesHelper

	before_filter :authenticate_user_logged_in

	def create
		@prize = Prize.new(prize_params)
		@prize.image = '/images/no_image.png' if params[:image].blank?
		if @current_user.can_manage_inventory
			if @prize.save
				flash[:title] = 'Success'
				flash[:notice] = 'Prize has been updated'
				StoreLog.new(:employee_id => @current_user.id, 
					:cashier_id => @current_user.id, 
					:prize_id => @prize.id,
					:trans => 'Created').save
				redirect_to :action => 'manage'
			else
				flash.now[:title] = 'Error'
				flash.now[:notice] = @prize.errors.messages
				render 'new'
			end
		else
			flash[:title] = 'Error'
			flash[:notice] = 'You do not have permission to edit items'
			redirect_to :action => 'index'
		end
	end

	def discontinue
		if @current_user.can_manage_inventory
			@prize = Prize.find(params[:id])
			stock_before = @prize.get_total_stock
			@prize.update_attributes(available: false)
			flash[:title] = 'Success'
			flash[:notice] = @prize.name + ' has been successfully discontinued from the shop!'
			StoreLog.new(:employee_id => @current_user.id, 
				:cashier_id => @current_user.id, 
				:prize_id => @prize.id,
				:trans => 'Discontinued',
				:stock_before => stock_before,
				:stock_after => 0).save
			redirect_to action: :manage
		else 
			flash[:title] = 'Error'
			flash[:notice] = 'You do not have permission to discontinue that item'
			redirect_to action: :index
		end
	end

	def edit
		@prize = Prize.find(params[:id])
	end

	def index
		@categories = get_categories
		@subcat_search_result = PrizeSubcat.search_store(params[:size], params[:color])
		@subcat_search_result_ids = Array.new
		@subcat_search_result.each { |p| @subcat_search_result_ids.push(p.prize_id) }
		@prizes = Prize.where(id: @subcat_search_result_ids)
		@prizes = @prizes.search_store(params[:name], params[:category])
		@featured = Prize.where(available: true, featured: true).group(:name)
		@filters = params.select { |p,k|  p if p == "color" || p == "name" || p == "size" || p == "category" }
	end

	def logs
		if @current_user.has_admin_access
			@store_logs = StoreLog.search(params[:customer_id], params[:cashier_id], params[:purchase_id])
		else
			flash.now[:title] = 'Error'
			flash.now[:notice] = 'You do not have permission to view these logs.'
			render 'logs'
		end
	end

	def manage
		@prizes = Prize.search(params[:id], params[:name], params[:available])
	end

	def new
		@prize = nil
		@prizes = Prize.all.group(:name).order(:name)
	end

	def show
		@prize = Prize.find(params[:id])
		@featured = Prize.first(5)
		@prize_subcats = PrizeSubcat.where(prize_id: @prize.id)
		@images = @prize_subcats.group(:image).map { |p| p.image if p.image != '' }
		if !@prize_subcats.blank?		
			@prize_subcats = PrizeSubcat.where(prize_id: @prize.id)
			@sizes = @prize_subcats.group(:size).map { |p| p.size }
			@colors = @prize_subcats.group(:color).map { |p| p.color }
			@brands = @prize_subcats.group(:brand).map { |p| p.brand }
			@chosen = PrizeSubcat.search(@prize.id, params[:size], params[:color], params[:brand]).first
			
		else
			flash[:title] = 'Error'
			flash[:notice] = 'Item is currently out of stock or discontinued.'
			redirect_to action: :index
		end
	end

	def stock
		@prize = Prize.find(params[:id])
	end

	def update
		@prize = Prize.find(params[:id])
		if(params.key?("cancel"))
        	redirect_to action: :manage
    	else
			if @current_user.can_manage_inventory
				if @prize.update_attributes(prize_params)
					@prize.update_attributes(image: '/images/no_image.png') if @prize.image.blank?
					flash[:title] = 'Success'
					flash[:notice] = 'Prize has been updated'
					StoreLog.new(:employee_id => @current_user.id, 
						:cashier_id => @current_user.id, 
						:prize_id => @prize.id,
						:trans => 'Updated').save
					redirect_to :action => 'manage'
				else
					flash.now[:title] = 'Error'
					flash.now[:notice] = @prize.errors.messages
					render 'edit'
				end
			else
				flash[:title] = 'Error'
				flash[:notice] = 'You do not have permission to edit items'
				redirect_to action: :index
			end
		end
	end

	private 
		def prize_params
			params.require(:prize).permit(:id, :name, :cost, :category, :must_order, :available, :image, :description, :featured)
		end

end

app/helpers/prizes_helper.rb
module PrizesHelper

	def get_categories
		categories = ["Accessories",
		"Apparel",
		"Appliances",
		"Decorative",
		"Electronics",
		"Hollywood Perks",
		"Miscellaneous",
		"Tickets"]

		return categories
	end

	def get_color_code(color)
		case color
		when "Black"
			return "#000000"
		when "Blue"
			return "#0000FF"
		when "Brown"
			return "#A52A2A"
		when "Dark Brown"
			return "#0000FF"
		when "Gold"
			return "#EAC117"
		when "Grey"
			return "#808080"
		when "Green"
			return "#008000"
		when "Light Brown"
			return "#de7848"
		when "Lime Green"
			return "#00FF00"
		when "Maroon"
			return "#800000"
		when "Navy"
			return "#0000A0"
		when "Orange"
			return "#FFA500"
		when "Pink"
			return "#FF00FF"
		when "Purple"
			return "#800080"
		when "Red"
			return "#FF0000"
		when "Sky Blue"
			return "#ADD8E6"
		when "Teal"
			return "#FFFF00"
		when "White"
			return "#FFFFFF"
		when "Yellow"
			return "#FFFF00"
		end

	end

end

app/views/prizes/_prize_form_contents.html.erb
<p><label for = "prize_name">Item Name</label>:<br>
<%= text_field 'prize', 'name', id: 'prize_name', class: 'form-control' %></p>

<p><label for = "prize_cost">Cost</label>:<br>
<%= text_field 'prize', 'cost', id: 'prize_cost', class: 'form-control' %></p>

<p><label for = "prize_cost">Category</label>:<br>
<%= select_tag 'prize[category]', options_for_select(get_categories), class: 'form-control' %>

<p><label for = "prize_image">Image Path (/images/image_path.png)</label>:<br>
<%= text_field 'prize', 'image', id: 'prize_image', class: 'form-control' %></p>

<p><%= label_tag('must_reserve', "Must be reserved and ordered?") %>
<%= check_box 'prize', 'must_order', {}, 'true', 'false' %></p>

<p><%= label_tag('featured', "Featured item: ") %>
<%= check_box 'prize', 'featured', {}, 'true', 'false' %></p>

<p><label for = "prize_image">Description</label>:<br>

<% if @prize.nil? %>
	<%= text_area_tag 'prize[description]', nil, size: "32x6", class: 'form-control' %>
<% else %>
	<%= text_area_tag 'prize[description]', @prize.description, size: "32x6", class: 'form-control' %>
<% end %>

<p class = "form-note">250 characters max</p>	

app/views/prizes/_prizes_choose.html.erb
<% if @prizes.blank? %>
	<p>None</p>
<% else %>
<div class="table-responsive">
	<table class = 'table-list' id = 'table-prizes-choose'>
		<tr class = "tr-list-head" >
			<td class = "td-list">Prize</td>
			<td class = "td-list">Cost</td>
			<td class = "td-list">Image</td>
		</tr>
		<% @prizes.each do |p|  %>
		<tr class = "tr-list">
			<td class = "td-list"> <%= p.name %> </td>
			<td class = "td-list"> <%= p.cost %> </td>
			<td class = "td-list"> <%= p.image %> </td>
		</tr>
		<% end %>
	</table>
</div>
<% end %>

app/views/prizes/_prizes_full.html.erb
<% if @prizes.blank? %>
	<p>None</p>
<% else %>
	<% @prizes.each do |p| %>
		<div class = "prize-list-container">
			<div class = "price-tag">$<%= p.cost %> Bucks</div>
			<div class = "prize-content">
				<p><b><%= p.name %></b></p>
				
				<p>In Stock: <%= p.stock %></p>
			</div>
			<div class = "prize-options">
				<% if @current_user.has_admin_access %>
					<%= link_to 'Edit', { action: :edit, id: p} %> | <%= link_to 'Delete', { controller: :prizes, action: :destroy, id: p.id} %>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/prizes/_prizes_grid.html.erb
<% if @prizes.blank? %>
	<p>None</p>
<% else %>
	<% @prizes.each_with_index do |p, i| %>
          <div class="col-md-3">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="prize-container" style="background-image: url('<%= p.get_first_image %>')">
                  <div class="header">
                    <div class = "price">$<%= p.cost %></div>
                  </div>
                </div>
                <div class="prize-info">
                  <%= link_to p.name, action: :show, id: p.id %>
                      <% @prize_subcat = PrizeSubcat.where(prize_id: p.id) %>
                  <% if p.must_order %>
                          <br/>Prize must be ordered
                      <% else %>
                          <br/><%= p.get_total_stock %> In Stock
                  <% end %>
                  <br/>
                  <% @prize_subcat.group(:color).each do |c|
                    if c.color != '' %>
                      <div class = "color" style="background-color:<%= get_color_code(c.color) %>""></div>
                    <% end end %>
                  <div class="prize-info--favorites img-hover">
                    <a href="/favorites/create?prize_id=<%= p.id %>"><span class="glyphicon glyphicon-heart image-responsive"></span></a>
                  </div>
                </div>
            </div>
          </div>
        </div>

	<% end %>
<% end %>



app/views/prizes/_prizes_manage.html.erb
<% if @prizes.blank? %>
	<p>None</p>
<% else %>
<div class="table-responsive">
	<table class = 'table table-striped table-condensed' id = 'table-prizes-small'>
		<thead>
			<th>ID</th>
			<th>Prize</th>
			<th>Category</th>
			<th>Cost</th>
			<th>Stock</th>
			<th>Must Reserve</th>
			<th>Available</th>
			<th>Featured</th>
			<th>Manage</th>
		</thead>
		<tbody>
			<% @prizes.each do |p|  %>
			<tr>
				<td> <%= p.id %> </td>
				<td> <%= p.name %> </td>
				<td> <%= p.category %> </td>
				<td> $<%= p.cost %> </td>
				<td> <%= p.get_total_stock %> </td>
				<td class="centered"> <%= image_tag 'check16dp.png' if p.must_order %> </td>
				<td class="centered"> <%= image_tag 'check16dp.png' if p.available %> </td>
				<td class="centered"> <%= image_tag 'check16dp.png' if p.featured %> </td>
				<td> <%= link_to 'Manage Stock', controller: :prize_subcats, action: :manage, id: p.id %> | <%= link_to 'Edit', { action: :edit, id: p} %> | <%= link_to 'Discontinue', { controller: :prizes, action: :discontinue, id: p.id} %> </td>
			</tr>
			<% end %>
		</tbody>
	</table>
	</div>
<% end %>

app/views/prizes/_prizes_small.html (2).erb
<% if @prizes.blank? %>
	<p>None</p>
<% else %>
	<% @prizes.each do |p|  %>
		<div class = "prize-list-container">
			<div class = "price-tag"><%= p.cost %> Bucks</div>
			<div class = "prize-content">
				<p><b><%= p.name %></b></p>
				
				<p>Quanitity: <%= p.get_quantity %></p>
			</div>
			<div class = "prize-options">
				<% if @current_user.has_admin_access %>
					<%= link_to 'Edit', { action: :edit, id: p} %> | <%= link_to 'Delete', { controller: :prizes, action: :destroy, id: p.id} %>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/prizes/_prizes_small.html.erb
<% if @prizes.blank? %>
	<p>None</p>
<% else %>
<div class="table-responsive">
	<table class = 'table table-condensed table-striped' id = 'table-prizes-small'>
		<thead>
			<th>ID</th>
			<th>Prize</th>
			<th>Name</th>
			<th>Brand</th>
			<th>Stock</th>
			<th>Cost</th>
			<th>Size</th>
			<th>Color</th>
			<th>Must Reserve</th>
		</thead>
		<tbody>
		<% @prizes.each do |p|  %>
			<tr class="tr-clickable">
				<td> <%= p.id %> </td>
				<td> <%= p.prize_id %> </td>
				<td> <%= p.name %> </td>
				<td> <%= p.brand %> </td>
				<td> <%= p.stock %> </td>
				<td> $<%= p.cost %> </td>
				<td> <%= p.size %> </td>
				<td> <%= p.color %> </td>
				<td> <%= image_tag 'check16dp.png' if p.must_order %> </td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>
<% end %>

app/views/prizes/edit.html.erb
<!-- START FLASH -->                     
<% if flash[:notice] %>
  <div class="alert alert-danger">
  <% flash[:notice].each do | k, m |
    flash[:notice][k].each do | e | %>
      <%= e %><br>
    <% end
  end %>
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span></button>
  </div>
<% end %>
<!-- END FLASH -->

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Home</a></li>  
    <li><a href="/prizes">Store</a></li>
    <li><a href="/prizes/manage">Manage</a></li>
    <li><%= @prize.name %></li>
    <li>Edit</li>                
</ul>
<!-- END BREADCRUMB -->  

<!-- START TITLE -->
<div class="page-title">                    
    <h2><span class="fa fa-shopping-cart"></span> Edit Prize</h2>
</div>
<!-- END TITLE -->

<div class="page-content-wrap">

  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default panel-body">
        <%= form_tag :action => 'update' do %>

          <%= render 'prize_form_contents' %>

          <%= submit_tag 'Save Changes', class: 'btn btn-primary' %>
          <%= button_tag 'Cancel', type: 'cancel', name: 'cancel', class: 'btn btn-primary' %>
        <% end -%>
      </div>
    </div>
  </div>
</div>

app/views/prizes/home.html.erb
<div class="row">
  <div class = "col-sm-8">
    <div class = "panel panel-default">
      <div class="panel-heading">News</div>
      <div class="panel-body">
        <center><%= render 'news_slideshow' %></center>
        <%= render 'newsfeed' %>
      </div>
    </div>


  </div>
			
  <div class = "col-sm-4">
      <div class = "panel panel-default">
        <div class="panel-heading">Leaderboards</div>
        <div class="panel-body">
          <%= render 'leaderboards' %>
        </div>
      </div>
  </div>

  <div class="col-sm-4">
    <div class="panel panel-default left-float">
      <div class="panel-heading">Spotlight Prize</div>
      <div class="panel-body">
        <%= render '/prizes/prizes_line_home' %>
      </div>
    </div>
  </div>
</div>

app/views/prizes/index.html.erb
<!-- START FLASH -->                     
<% if flash[:title] == "Error" %>
    <div class="alert alert-danger"><%= flash[:notice] %><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span></button></div>
<% elsif flash[:title] == "Success" %>
    <div class="alert alert-success"><%= flash[:notice] %><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span></button></div>
<% end %>
<!-- END FLASH -->

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Home</a></li>    
    <li><a href="/prizes">Store</a></li>                  
</ul>
<!-- END BREADCRUMB -->  

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

  <div class="row">

    <div class="col-md-9">
      <div class="panel panel-default panel-body">
        <div class = "shop_banner">
          <img src="/images/bucks_shop_logo.png" class = "shop-banner-logo">
        </div>



        <div class = "featured-wrapper">
          <h1>Spotlight Prizes</h1>
          <%= render 'prizes_featured' %>

        </div>

        <h1>Available Prizes</h1>
          <%= render 'prizes_grid' %>
      </div>
    </div>

    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Filter</h3><ul class="list-tags">
          <% @filters.each do |f| %>
          	<% if f[1] != "" %>
            	<li><a href="#"><span class="fa fa-tag"></span><%= f[1] %></a></li>
          	<% end %>
          <% end %>
        </ul>
        </div>
        <div class="panel-body">
        <%= form_tag (''), :method => 'get', :id => 'prize_search' do %>
          <%= text_field_tag :name, params[:name], class: 'form-control', placeholder: 'Name' %><br/>
          <%= select_tag :color, options_for_select([
            [],
            ['Black'],
            ['Blue'],
            ['Brown'],
            ['Dark Brown'],
            ['Gold'],
            ['Grey'],
            ['Green'],
            ['Light Brown'],
            ['Lime Green'],
            ['Maroon'],
            ['Navy'],
            ['Orange'],
            ['Pink'],
            ['Purple'],
            ['Red'],
            ['Sky Blue'],
            ['Teal'],
            ['White'],
            ['Yellow']]), include_blank: "Color", class: 'form-control' %><br/>
          <%= select_tag :size, options_for_select([
            [],
            ['XS'],
            ['S'],
            ['M'],
            ['L'],
            ['XL'],
            ['XXL'],
            ['XXXL']]), include_blank: "Size", class: 'form-control' %>
            <br/>
            <div class="list-group border-bottom">
            	<% @categories.each do |c| %>
            			<% if c == params[:category] %>
              			<%= link_to prizes_path(name: params[:name], color: params[:color], size: params[:size], category: c), class: "list-group-item active"  do %>
              			<%= c %><span class="badge badge-primary"><%= @prizes.where(category: c).count %></span>
              			<% end %>
              		<% else %>
              			<%= link_to prizes_path(name: params[:name], color: params[:color], size: params[:size], category: c), class: "list-group-item"  do %>
              			<%= c %><span class="badge badge-primary"><%= @prizes.where(category: c).count %></span>
              			<% end %>
              		<% end %>
              <% end %>
          	</div>  
          	<br/>
          	<%= submit_tag 'Filter', remote: true, id: 'search_prize_button', class: 'btn btn-primary' %>
            <%= link_to 'Reset', :prizes, class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>

    
    </div>
  </div>
</div>
        



app/views/prizes/logs.html.erb
<!-- START FLASH -->                     
<% if flash[:title] == "Error" %>
    <div class="alert alert-danger"><%= flash[:notice] %><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span></button></div>
<% elsif flash[:title] == "Success" %>
    <div class="alert alert-success"><%= flash[:notice] %><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span></button></div>
<% end %>
<!-- END FLASH -->

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Home</a></li>  
    <li><a href="/prizes">Store</a></li>
    <li>Logs</li>              
</ul>
<!-- END BREADCRUMB -->  

<!-- START TITLE -->
<div class="page-title">                    
    <h2><span class="fa fa-pencil-square-o"></span> Store Logs</h2>
</div>
<!-- END TITLE -->

<div class="page-content-wrap">
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= form_tag (''), :method => 'get', :id => 'employee_search' do %>
              <div class="col-md-3">
                <%= text_field_tag :customer_id, params[:customer_id], placeholder: 'Customer ID', class: "form-control" %>
              </div>
              <div class="col-md-3">
                <%= text_field_tag :cashier_id, params[:cashier_id], placeholder: 'Cashier ID', class: "form-control" %>
              </div>
              <div class="col-md-3">
                <%= text_field_tag :purchase_id, params[:purchase_id], placeholder: 'Purchase #', class: "form-control" %>
              </div>
              <div class="col-md-3">
                <%= submit_tag 'Search', id: 'store_search', class: "btn btn-primary" %>
              </div> 
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default panel-body">
        <% if @store_logs.blank? %>
          <p>There is no store log information to show. Use the fields given to search for a logged transaction.</p>
        <% else %>
          <div class="table-responsive">
          <table class = 'table-condensed table-striped table-bordered'>
            <thead>
              <th>Employee</th>
              <th>Employee Name</th>
              <th>Cashier</th>
              <th>Cashier Name</th>
              <th>Transaction</th>
              <th>Prize</th>
              <th>Purchase #</th>
              <th>Stock Before</th>
              <th>Stock After</th>
              <th>Time</th>
            </thead>
            <tbody>
              <% @store_logs.each do |l|
                @employee = Employee.find(l.employee_id)
                @cashier = Employee.find(l.cashier_id)
                @prize = Prize.find(l.prize_id)
              %>
              <tr>
                <td> <%= @employee.id %> </td>
                <td> <%= @employee.first_name + " " + @employee.last_name %> </td>
                <td> <%= @cashier.id %> </td>
                <td> <%= @cashier.first_name + " " + @cashier.last_name %> </td>
                <td> <%= l.trans %> </td>
                <td> <%= @prize.name %> </td>
                <td> <%= l.purchase_id %> </td>
                <td> <%= l.stock_before %> </td>
                <td> <%= l.stock_after %> </td>
                <td> <%= l.created_at %> </td>
              </tr>
              <% end %>
            </tbody>
          </table>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/prizes/new.html.erb
<!-- START FLASH -->                     
<% if flash[:notice] %>
  <div class="alert alert-danger">
  <% flash[:notice].each do | k, m |
    flash[:notice][k].each do | e | %>
      <%= e %><br>
    <% end
  end %>
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span></button>
  </div>
<% end %>
<!-- END FLASH -->

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Home</a></li>  
    <li><a href="/prizes">Store</a></li>
    <li><a href="/prizes/manage">Manage</a></li>
    <li>New</li>                
</ul>
<!-- END BREADCRUMB -->  

<!-- START TITLE -->
<div class="page-title">                    
    <h2><span class="fa fa-shopping-cart"></span> New Prize</h2>
</div>
<!-- END TITLE -->

<div class="page-content-wrap">

  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default panel-body">
        <%= form_tag :action => 'create' do %>

          <%= render 'prize_form_contents' %>

          <%= submit_tag 'Submit', class: 'btn btn-primary' %>
        <% end -%>
      </div>
    </div>
  </div>
</div>

