config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get '/'                             => 'employees#home'
  get 'report'                        => 'admin#issue'
  post 'report_deliver'               => 'admin#issue_deliver'
  get 'feedback'                      => 'admin#feedback'
  post 'feedback_deliver'             => 'admin#feedback_deliver'

  get 'employees'                     => 'employees#index'
  get 'employees/team'                => 'employees#team'
  get 'employees/import'              => 'employees#import'
  get 'employees/change'              => 'employees#change_password'
  get 'employees/change/complete'     => 'employees#change_password_finish'
  post 'employees/change/complete'    => 'employees#change_password_finish'
  get 'employees/:id'                 => 'employees#show', as: :employee
  get 'employees/:id/achievements'    => 'employees#achievements'
  get 'employees/analyze/:id'         => 'employees#analyze'

  get 'bucks'                         => 'bucks#index'
  get 'bucks/new'                     => 'bucks#new'
  get 'bucks/import'                  => 'bucks#import'
  post 'bucks'                        => 'bucks#create'
  get 'bucks/issued'                  => 'bucks#issued'
  get 'bucks/pending'                 => 'bucks#pending'
  get 'bucks/pending/:id'             => 'bucks#approve'
  post 'bucks/pending/:id'            => 'bucks#update'
  get 'bucks/:id'                     => 'bucks#show', as: :buck
  post 'bucks/new'                    => 'bucks#search'
  get 'bucks/delete/:id'              => 'bucks#delete'

  get 'purchase/start_manage'         => 'purchases#start_manage'
  get 'purchase/start_purchase'       => 'purchases#start_purchase'
  get 'purchase/manage'               => 'purchases#manage'
  get 'purchase/refund'               => 'purchases#refund'
  get 'purchase/finish/:id'           => 'purchases#finish'
  post 'purchase/finish/:id'          => 'purchases#complete'
  get 'purchase/reserved'             => 'purchases#reserved'
  get 'exchange'                      => 'purchases#exchange'

  get 'prizes'                        => 'prizes#index'
  get 'prizes/orders'                 => 'purchases#orders_personal'
  get 'prizes/manage'                 => 'prizes#manage'
  get 'prizes/new'                    => 'prizes#new'
  post 'prizes'                       => 'prizes#create'
  get 'prizes/edit/:id'               => 'prizes#edit'
  get 'prizes/:id'                    => 'prizes#show'
  post 'prizes/:id'                   => 'purchases#complete'
  post 'prizes/edit/:id'              => 'prizes#update'
  get 'prizes/discontinue/:id'        => 'prizes#discontinue'
  get 'prizes/:id/stock'              => 'prizes#stock'

  get 'prizes/manage/:id'             => 'prize_subcats#manage'
  post 'prizes/manage/:id'            => 'prize_subcats#create'
  get 'prizes/manage/:id/new'         => 'prize_subcats#new'
  get 'prizes/manage/type/:id'        => 'prize_subcats#edit'
  post 'prizes/manage/type/:id'       => 'prize_subcats#update'

  get 'jobs'                          => 'jobs#index'
  get 'jobs/import'                   => 'jobs#import'

  get 'login'                         => 'sessions#new'
  post 'login'                        => 'sessions#create'
  get 'logout'                     => 'sessions#destroy'

  get 'admin/depts'                   => 'departments#edit'
  post 'admin/depts'                  => 'departments#update'
  get 'admin/depts/approver'          => 'departments#approvers'
  get 'admin/depts/approver_add'      => 'departments#approver_add'
  get 'admin/logs/bucks'              => 'bucks#logs'
  get 'admin/logs/store'              => 'prizes#logs'
  get 'admin/bucks/analyze'           => 'bucks#analyze'
  get 'admin/orders'                  => 'purchases#orders'
  get 'admin/orders/pickup/:id'       => 'purchases#pickup'
  get 'admin/orders/drop/:id'         => 'purchases#drop'
  get 'admin/orders/confirm/:id'      => 'purchases#confirm'
  get 'admin/hard_reset'              => 'override#verify'
  get 'admin/hard_reset/:key'         => 'override#process'

  get 'mail/optout/:id'               => 'mailer#opt_out'

  get 'roles'                         => 'roles#index'
  get 'roles/new'                     => 'roles#new'
  get 'roles/edit/:id'                => 'roles#edit'
  get 'roles/assign/:id'              => 'roles#assign'
  post 'roles/edit/:id'               => 'roles#update'
  post 'roles'                        => 'roles#create'
  get 'roles/assign/:id/add'          => 'roles#add_to_role'
  get 'roles/assign/:id/remove'       => 'roles#remove_from_role'
  get 'roles/delete/:id'              => 'roles#delete'

  get 'favorites'                     => 'favorites#index'
  get 'favorites/create/'             => 'favorites#create'
  get 'favorites/delete'              => 'favorites#delete'

end

app/controllers/bucks_controller.rb
class BucksController < ApplicationController
	include ApplicationHelper
	include BucksHelper
	include EmployeesHelper
	include SessionsHelper
	include BucksImportHelper

	helper_method :sort_buck_column, :sort_buck_direction
	before_filter :authenticate_user_logged_in

	def analyze
		if @current_user.has_admin_access
			@departments = Department.all
			@months = Buck.group("month(bucks.approved_at)").map { |b| b.approved_at.strftime("%B") if !b.approved_at.nil? } 
			@years = Buck.group("year(bucks.approved_at)").map { |b| b.approved_at.strftime("%Y") if !b.approved_at.nil? }
			@bucks = Buck.search_dept(params[:department], params[:month], params[:year]).order(sort_buck_column + " " + sort_buck_direction)

			if !params[:department].blank? && !params[:month].blank? && !params[:year].blank?
				@department = Department.find(params[:department])
				@month = params[:month] if !params[:month].blank?
				@year = params[:year] if !params[:year].blank?
				@department_budget = @department.get_budget_overall
				@budget_per_employee = @department.get_budget_per_employee
				@employees = Employee.where(department_id: @department.id).order(:last_name).select { |e| e.can_issue_bucks }
			end
		else 
			flash.now[:title] = 'Error'
			flash.now[:notice] = 'You do not have permission to view that buck.'
			render 'show'
		end
	end

	def approve
		if @current_user.can_view_buck(Buck.find(params[:id]))
			@buck = Buck.find(params[:id])
		else 
			flash.now[:title] = 'Error'
			flash.now[:notice] = 'You do not have permission to view that buck.'
			render 'show'
		end
	end

	def create

		@buck = Buck.new(bucks_params)
		valid_buck = true

		if params[:buck][:employee_id] == ''
			@buck.errors.add(:employee_id, "Must enter a valid Employee ID")
			valid_buck = false
		end

		if @buck.reason_short == ''
			@buck.errors.add(:reason_short, "Must provide a reason for issuing buck")
			valid_buck = false
		end

		if @buck.employee_id == @current_user.IDnum
			@buck.errors.add(:reason_short, "You cannot issue bucks to yourself")
			valid_buck = false
		end

		if (@buck.reason_short == 'Customer Service' || @buck.reason_short == 'Other') && @buck.reason_long == ''
			@buck.errors.add(:reason_long, "Must provide a reason for issuing buck if issuing for Customer Service or Other")
			valid_buck = false
		end

		if valid_buck
			@buck.assignedBy = Employee.find(session[:id]).id
			@employee = Employee.find(@buck.employee_id)
			@buck.department_id = @employee.department_id
			@buck.number = assign_buck_number
			if @buck.needs_approval(@current_user, @employee)
				@buck.status = "Pending"
			else
				@buck.status = "Active"
				@buck.expires = Time.now.advance(:years => +1)
				@buck.approved_at = Time.now
			end
			
			@buck.save

			if @buck.reason_short == 'Other'
				Mailer.pending_buck_approval(@current_user, @buck).deliver_now
			else
				Mailer.notify_employee(@buck, @employee).deliver_now
			end

			buck_log_params = { :buck_id => @buck.id, 
				:event => 'Issued', 
				:performed_id => @current_user.id,
				:recieved_id => @employee.id,
				:value_before => @buck.value,
				:value_after => @buck.value,
				:status_before => @buck.status,
				:status_after => @buck.status }
			BuckLog.new(buck_log_params).save

			
			flash[:title] = 'Success'
			flash[:notice] = 'Buck has been submitted!'
			redirect_to :action => 'show', id: @buck.id
			
		else
			flash[:title] = 'Error'
			flash[:notice] = @buck.errors.messages
			redirect_to :action => 'new'
		end
	end

	def delete
		@buck = Buck.find(params[:id])
		
		flash[:title] = 'Success'
		flash[:notice] = 'Buck ' + params[:id] + ' has been successfully voided!'

		buck_log_params = { :buck_id => @buck.id, 
			:event => 'Voided', 
			:performed_id => @current_user.id,
			:recieved_id => @current_user.id,
			:value_before => @buck.value,
			:value_after => @buck.value,
			:status_before => @buck.status,
			:status_after => 'Void' }
		BuckLog.new(buck_log_params).save

		@buck.update_attributes(status: 'Void')
		redirect_to :action => 'index'
	end

	def import
		import_bucks
		redirect_to action: 'index'
	end
	
	def index
		if @current_user.has_admin_access || @current_user.can_view_all
			
			if params[:sort] == 'employeeName'
				@bucks = Buck.search(params[:search_id], params[:search_recipient_id], params[:search_issuer_id]).sort_by(&:get_employee_name)
			else
				@bucks = Buck.search(params[:search_id], params[:search_recipient_id], params[:search_issuer_id]).order(sort_buck_column + " " + sort_buck_direction)
			end
		else
			flash.now[:title] = 'Error'
			flash.now[:notice] = 'You do not have permission to view all bucks.'
			render 'index'
		end
	end

	def logs
		if @current_user.has_admin_access
			@buck_logs = BuckLog.search(params[:buck_id], params[:performed_id], params[:recieved_id])
		else
			flash.now[:title] = 'Error'
			flash.now[:notice] = 'You do not have permission to view these logs.'
			render 'logs'
		end
	end

	def new
		@employees = Employee.search(params[:search_id], params[:search_first_name], params[:search_last_name]).where(status: 'Active')
	end

	def pending
		if @current_user.can_approve_bucks
			@bucks = @current_user.get_pending_bucks
		else
			flash.now[:title] = 'Error'
			flash.now[:notice] = 'You do not have permission to approve bucks.'
			render 'pending'
		end
	end

	def show
		if @current_user.can_view_buck(Buck.find(params[:id]))
			@buck = Buck.find(params[:id])
		else 
			flash.now[:title] = 'Error'
			flash.now[:notice] = 'You do not have permission to view that buck.'
			render 'show'
		end
	end

	def update
		@buck = Buck.find(params[:id])

		buck_log_params = { :buck_id => @buck.id,  
			:performed_id => @current_user.id,
			:recieved_id => @buck.employee_id,
			:value_before => @buck.value,
			:status_before => @buck.status }
		
		if @current_user.can_approve_bucks || @current_user.has_admin_access 
			if params[:decision] == 'Approve'
				@buck.update_attribute(:status, 'Active')
				@buck.update_attribute(:expires, Time.now.advance(:years => +1))
				@buck.update_attribute(:approved_at, Time.now)
				@buck.update_attribute(:value, params[:buck][:value])

				buck_log_params[:value_after] = params[:buck][:value]
				buck_log_params[:event] = 'Approved'
				buck_log_params[:status_after] = 'Approved'

				flash[:title] = 'Success'
				flash[:notice] = 'Buck has been approved'
				BuckLog.new(buck_log_params).save

				approved_buck_log_params = { :buck_id => @buck.id,  
					:performed_id => @buck.assignedBy,
					:recieved_id => @buck.employee_id,
					:event => 'Activated',
					:value_before => @buck.value,
					:value_after => params[:buck][:value],
					:status_before => 'Pending',
					:status_after => 'Active' }
				BuckLog.new(approved_buck_log_params).save

				Mailer.notify_issuer(@buck, Employee.find(@buck.assignedBy), Employee.find(@buck.employee_id), "Approved", "Approved").deliver_now

				redirect_to @buck
			elsif params[:decision] == 'Deny'
				@buck.update_attribute(:status, 'Denied')
				@buck.update_attribute(:value, 0)
				buck_log_params[:value_after] = 0
				buck_log_params[:event] = 'Denied'
				buck_log_params[:status_after] = 'Void'

				flash[:title] = 'Success'
				flash[:notice] = 'Buck has been denied'
				BuckLog.new(buck_log_params).save

				Mailer.notify_issuer(@buck, Employee.find(@buck.assignedBy), Employee.find(@buck.employee_id), "Denied", params[:buck][:denial_reason]).deliver_now

				redirect_to @buck
			else
				flash.now[:title] = 'Error'
				flash.now[:notice] = @buck.errors.messages
				render 'approve'
			end
		else
			flash[:title] = 'Error'
			flash[:notice] = 'You do not have permission to approve bucks'
			redirect_to :action => 'index'
		end
	end

	private 
	def bucks_params
		params.require(:buck).permit(:value, :reason_short, :reason_long, :prize_id, :decision, :employee_id)
	end

	def makePurchase(prize, employee, item)
		perform_bucks_purchase_transaction(prize, employee)
		item.update_attribute(:status, 'Purchased')

		store_log_params = { :employee_id => employee.id, 
				:cashier_id => @current_user.id, 
				:prize_id => prize.id,
				:item_barcode => item.barcode,
				:trans => "Purchased",
				:balance_before => balance_before,
				:balance_after => employee.get_bucks_balance }

		StoreLog.new(store_log_params).save
	end

	def request_order(prize, employee)
		perform_bucks_purchase_transaction(prize, employee)
		@item = Item.new(name: prize.name, prize_id: prize.id, status: "Ordered")
		@item.save

		store_log_params = { :employee_id => employee.id, 
				:cashier_id => @current_user.id, 
				:prize_id => prize.id,
				:trans => "Ordered",
				:item_id => @item.id,
				:balance_before => employee.get_bucks_balance,
				:balance_after => employee.get_bucks_balance 
			}
		StoreLog.new(store_log_params).save
	end

	def perform_bucks_purchase_transaction(prize, employee)
		balance_before = employee.get_bucks_balance
		spent = 0

		while spent < prize.cost
			@oldest_buck = Buck.where(status: ['Active', 'Partial']).where(employee_id: @employee.id).order(:approved_at).first
			spent = spent + @oldest_buck.value

			buck_log_params = { :buck_id => @oldest_buck.id, 
				:event => 'Spent', 
				:performed_id => @current_user.id,
				:recieved_id => employee.id,
				:value_before => @oldest_buck.value,
				:status_before => @oldest_buck.status,
				:purchased => prize.id }

			if spent > prize.cost
				@oldest_buck.update_attribute(:value, (spent - prize.cost))
				@oldest_buck.update_attribute(:status, 'Partial')

				buck_log_params[:value_after] = spent - prize.cost
				buck_log_params[:status_after] = 'Partial'
			else
				@oldest_buck.update_attribute(:status, 'Redeemed')
				buck_log_params[:status_after] = 'Redeemed'
				buck_log_params[:value_after] = 0
			end

			BuckLog.new(buck_log_params).save
		end
	end

end

app/helpers/bucks_helper.rb
module BucksHelper
	include SessionsHelper

	def assign_buck_number
		@highest_buck = Buck.order(number: :desc).first
		return @highest_buck.number + 1
	end

	def can_employee_afford_prize(employee, prize)
		get_bucks_balance(employee) > prize.cost
	end

	def getBuckValue(reason)
		if reason.eql?("A+ Service")
			return 20
		elsif reason.eql?("Attendance")
			return 3
		elsif reason.eql?("Shift Coverage")
			return 2
		elsif reason.eql?("Customer Service")
			return 5
		elsif reason.eql?("Community Involvement")
			return 3
		else
			return 10
		end
	end

	def p_class_for_budget(used, budget)
		if used <= budget
			return 'text-success'
		elsif used > budget && used < ((budget * 0.15) + budget)
			return 'text-warning'
		else
			return 'text-danger'
		end
	end

end

app/views/bucks/_analyze_budget_list.html.erb
<% if @employees.blank? %>
	<p>There is no employee information to show.</p>
<% else 
  budget_per_employee = @department.get_budget_per_employee %>
  <div class="table-responsive">
	<table class = 'table table-striped table-condensed'>
		<thead>
			<th>Team Member ID</th>
			<th>Name</th>
			<th>Position</th>
			<th>Issued</th>
			<th>% of Budget</th>
			<th>% of Dept Budget</th>
		</thead>
		<tbody>
			<% @employees.each do |e| 
				budget_used = e.get_personal_budget_used(@month_num, @year)
				%>
				<tr class = "tr-clickable" onclick=" window.document.location = '/employees/analyze/<%= e.IDnum %>?utf8=✓&month=<%= @month %>&year=<%= @year %>&commit=Show'; ">
				<td> <%= e.id %> </td>
				<td> <%= e.first_name + " " + e.last_name %> </td>
				<td> <%= Job.find(e.job_id).title %> </td>
				<td> <%= budget_used %> </td>
				<td> <p class = <%= p_class_for_budget(budget_used, budget_per_employee)%>><%= e.get_personal_budget_used_percent(@month_num, @year) %>%</p> </td>
				<td> <p class = <%= p_class_for_budget(budget_used, budget_per_employee)%>><%= e.get_department_budget_used_percent(@month_num, @year) %>%</p> </td>
			</tr>
			<% end %>
		</tbody>
	</table>
	</div>
<% end %>

app/views/bucks/_analyze_budget_report.html.erb
<div class="row">
	<div class="col-md-4">
	<% budget_used = @current_user.get_personal_budget_used(@month_num, @year) %>
	<div class="table-responsive">
	<table class="table table-condensed">
		<tr>
			<td>Department Budget: </td>
			<td> <%= @department_budget %> </td>
		</tr>
		<tr>
			<td>Department Budget Used: </td>
			<td> <%= @department.get_budget_used(@month_num, @year) %> / <%= @department_budget %> 
			<p class = <%= p_class_for_budget(budget_used, @department_budget)%>> (<%= @department.get_budget_used_percent(@month_num, @year) %>%)</p></td>
		</tr>
		<tr>
			<td>A+ Service: </td>
			<td> <%= @bucks.where(reason_short: "A+ Service").count %> </td>
		</tr>
		<tr>
			<td>Attendance: </td>
			<td> <%= @bucks.where(reason_short: "Attendance").count %> </td>
		</tr>
		<tr>
			<td>Community Involvement: </td>
			<td> <%= @bucks.where(reason_short: "Community Involvement").count %> </td>
		</tr>
		<tr>
			<td>Customer Service: </td>
			<td> <%= @bucks.where(reason_short: "Customer Service").count %> </td>
		</tr>
		<tr>
			<td>Shift Coverage: </td>
			<td> <%= @bucks.where(reason_short: "Shift Coverage").count %> </td>
		</tr>
		<tr>
			<td>Other: </td>
			<td> <%= @bucks.where(reason_short: "Other").count %> </td>
		</tr>
	</table>
	</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<%= render 'analyze_budget_list' %>
	</div>
</div>

app/views/bucks/_buck_detail.html.erb
<% if !@buck.nil? %>
    <h1>Buck #<%= @buck.id %></h1>
    <% @employee = Employee.find(@buck.employee_id) %>
    <% @assignedBy = Employee.find(@buck.assignedBy) %>

    <div class="buck-container">
      <div><img class="buck-container--logo" src="/images/banner_logo.png"></div>
      <div class="buck-container--info-left">
        TEAM MEMBER:
        <br>FROM:
        <br>DEPARTMENT:
        <br>DATE:
      </div>

      <div class="buck-container--info-right">
              <textarea disabled class="buck-container--info-textarea ">
                <%= @employee.full_name %>
              </textarea>
        <br><textarea disabled class="buck-container--info-textarea ">
                <%= @assignedBy.full_name %>
              </textarea>
        <br><textarea disabled class="buck-container--info-textarea ">
                <%= Department.find(@buck.department_id).name %>
              </textarea>
        <br><textarea disabled class="buck-container--info-textarea ">
                <%= @buck.approved_at %>
              </textarea>
      </div>
      <div class="buck-container--other-info">
      OTHER: CAN BE NO MORE THAN 10 BUCKS
      <br><textarea disabled class="buck-container--info-textarea-other ">
                         <%= @buck.reason_long %>
                      </textarea>
      <br><p>Number Of Bucks To Be Rewarded: <%= @buck.value %></p>
    </div>
      <br>
     <div class="bucks-container--other-right">
      <div class="buck-container--type-area">
        <br><center><text class="buck-container--big-font"> BUCK AWARDED FOR:</text>
        <br><text class="buck-container-cursive"><%= @buck.reason_short %></text></center>

        <br>
        <div class="buck-container--director">
          DIRECTOR SIGN OFF FOR "OTHER"
          <br><textarea disabled class="buck-container--info-textarea ">
              </textarea>
        </div>
      </div>
     </div>
    </div>

<% end %>



app/views/bucks/_bucks_monthly_mini.html.erb
<% if @bucks_month.blank? %>
	<p>None</p>
<% else %>
<div class="table-responsive">
	<table class = 'table-list'>
		<tr class = "tr-list-head" >
			<td class = "td-list"><%= buck_sortable "number" %></td>
			<td class = "td-list"><%= buck_sortable "value" %></td>
			<td class = "td-list"><%= buck_sortable "reason_short" %></td>
			<td class = "td-list"><%= buck_sortable "status" %></td>
		</tr>
		<% @bucks_month.each do |b|  %>
		<tr class = "tr-list" onclick=" window.document.location = '<%= buck_path(b) %>'; ">
			<td class = "td-list"> <%= b.number %> </td>
			<td class = "td-list"> <%= b.value %> </td>
			<td class = "td-list"> <%= b.reason_short %> </td>
			<td class = "td-list"> <%= b.status %> </td>
		</tr>
		<% end %>
	</table>
</div>
<% end %>

app/views/bucks/_bucks_pending.html.erb
<% if @bucks.blank? %>
	<p>None</p>
<% else %>
	<div class="table-responsive">
		<table class="table table-striped">
			<thead>
				<th><%= buck_sortable "number" %></th>
				<th><%= buck_sortable "employee_id" %></th>
				<th>Employee Name</th>
				<th>Department</th>
				<th><%= buck_sortable "value" %></th>
				<th><%= buck_sortable "assignedBy" %></th>
				<th>Department</th>
				<th><%= buck_sortable "reason_short" %></th>
				<th><%= buck_sortable "status" %></th>
				<th><%= buck_sortable "created_at" %></th>
			</thead>
			<tbody>
			<% @bucks.each do |b| 
				@assignedTo = Employee.find(b.employee_id) 
				@assignedBy = Employee.find(b.assignedBy) %>
			<tr class = "tr-list" onclick=" window.document.location = 'pending/<%= b.id %>'; ">
				<td> <%= b.number %> </td>
				<td> <%= b.employee_id %> </td>
				<td> <%= @assignedTo.first_name + " " + @assignedTo.last_name %> </td>
				<td> <%= Department.find(b.department_id).name %> </td>
				<td> <%= b.value %> </td>
				<td> <%= @assignedBy.first_name + " " + @assignedBy.last_name %> </td>
				<td> <%= Department.find(@assignedBy.department_id).name %> </td>
				<td> <%= b.reason_short %> </td>
				<td> <%= b.status %> </td>
				<td> <%= l b.created_at.localtime %> </td>
			</tr>
			<% end %>
			</tbody>
		</table>
	</div>
<% end %>

app/views/bucks/_issued_by_department.html.erb
<h1>Bucks Issued by <%= @department.name %> for <%= Time.now.strftime("%B") %> <%= Time.now.strftime("%Y") %></h1>

<div id = "bucks_table">
	<%= render 'bucks_route_detail' %>
</div>

app/views/bucks/_issued_by_me.html.erb
<h1>Your Bucks Issued for <%= Time.now.strftime("%B") %> <%= Time.now.strftime("%Y") %></h1>

<div id = "bucks_table">
	<%= render 'bucks_route_detail' %>
</div>

app/views/bucks/analyze.html.erb
<!-- START FLASH -->                     
<% if flash[:title] == "Error" %>
    <div class="alert alert-danger"><%= flash[:notice] %><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span></button></div>
<% elsif flash[:title] == "Success" %>
    <div class="alert alert-success"><%= flash[:notice] %><button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span></button></div>
<% end %>
<!-- END FLASH -->

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><a href="/bucks">Bucks</a></li>
    <li>Analyze</li>               
</ul>
<!-- END BREADCRUMB -->  

<!-- START TITLE -->
<div class="page-title">                    
    <h2><span class="fa fa-tachometer"></span> Analayze Department Budgets</h2>
</div>
<!-- END TITLE -->

<div class="page-content-wrap">

  <div class="page-content-wrap">
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <div class="panel panel-default">
          <div class="panel-body">
            <%= form_tag (''), :method => 'get', :id => 'department_filter' do %>
              <div class="col-md-3">
                <%= select_tag :department, options_from_collection_for_select(@departments, "id", "name"), include_blank: "Department", class: "form-control" %>
              </div>
              <div class="col-md-3">
                <%= select_tag :month, options_for_select(@months), include_blank: "Month", class: "form-control" %>
              </div>
              <div class="col-md-3">
                <%= select_tag :year, options_for_select(@years), include_blank: "Year", class: "form-control" %>
              </div>
              <div class="col-md-3">
                <%= submit_tag 'Show', id: 'department_filter_button', class: "btn btn-primary" %>
              </div> 
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default panel-body">
        <% if !@department.nil? && !@month.nil? && !@year.nil? %>
          <h2>Budget Report: <%= @department.name %> (<%= @month %>, <%= @year %>)</h2>
          <% @month_num = Date::MONTHNAMES.index(@month) %>
          <%= render 'analyze_budget_report' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bucks/approve.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default panel-body">

        <% if flash[:title] == "Error" %>
          <div class="notice-error"><%= flash[:notice] %></div>
        <% elsif flash[:title] == "Success" %>
          <div class="notice-success"><%= flash[:notice] %></div>
        <% end %>

        <%= render 'buck_detail' %>

        <div class = "inline-form-container">
          <%= form_tag :action => 'update' do %>

            <label for = "buck-value">Approving Value:</label>
              <%= text_field 'buck', 'value', value: @buck.value %>
              <%= hidden_field_tag :id, @buck.id %>
              <%= hidden_field_tag :decision, 'Approve' %>
              <%= submit_tag 'Approve' %>
          <% end -%>
          <br/><br/>
          <%= form_tag :action => 'update' do %>
            <label for = "buck-value">Reason for Denial:</label>
            <%= text_area_tag 'buck[denial_reason]', nil, size: "32x6", id: 'reason_long' %>
            <%= hidden_field_tag :id, @buck.id %>
            <%= hidden_field_tag :decision, 'Deny' %>
            <%= submit_tag 'Deny' %>
          <% end -%>

        </div>
     </div>
  </div>
</div>